"""kinect-next -- a modern, fast, strictly-typed library for Microsoft Kinect v2.

Importing this package is side-effect free and works on any platform; the Kinect
SDK runtime (``Kinect20.dll``) is only required once you call
:meth:`KinectSensor.open`.
"""

from __future__ import annotations

__version__ = "2.0.0"

from kinect_next.aio import AsyncKinectSensor
from kinect_next.core import (
    Activity,
    Appearance,
    AudioBeamMode,
    AudioController,
    AudioStreamError,
    ColorImageFormat,
    COMOperationError,
    CoordinateMapper,
    DetectionResult,
    Expression,
    FrameEdges,
    HandState,
    JointType,
    KinectAudioCalibrationState,
    KinectError,
    KinectNotAvailableError,
    KinectSensor,
    KinectTimeoutError,
    PointCloudData,
    StreamNotEnabledError,
    StreamType,
    TrackingConfidence,
    TrackingState,
)
from kinect_next.models import (
    AudioBeamSubFrame,
    AudioFrame,
    Body,
    BodyIndexFrame,
    ColorCameraSettings,
    ColorFrame,
    DepthFrame,
    FrameSet,
    Hand,
    InfraredFrame,
    Joint,
    JointCollection,
    LongExposureInfraredFrame,
    Point2D,
    Quaternion,
    Vector3,
    Vector4,
)
from kinect_next.utils import (
    SKELETON_BONES,
    draw_all_skeletons,
    draw_audio_radar,
    draw_audio_visual_overlay,
    draw_body_skeleton,
    find_speaking_body,
    save_point_cloud_ply,
    to_open3d_point_cloud,
)

__all__ = [
    "SKELETON_BONES",
    "Activity",
    "Appearance",
    "AsyncKinectSensor",
    "AudioBeamMode",
    "AudioBeamSubFrame",
    "AudioController",
    "AudioFrame",
    "AudioStreamError",
    "Body",
    "BodyIndexFrame",
    "COMOperationError",
    "ColorCameraSettings",
    "ColorFrame",
    "ColorImageFormat",
    "CoordinateMapper",
    "DepthFrame",
    "DetectionResult",
    "Expression",
    "FrameEdges",
    "FrameSet",
    "Hand",
    "HandState",
    "InfraredFrame",
    "Joint",
    "JointCollection",
    "JointType",
    "KinectAudioCalibrationState",
    "KinectError",
    "KinectNotAvailableError",
    "KinectSensor",
    "KinectTimeoutError",
    "LongExposureInfraredFrame",
    "Point2D",
    "PointCloudData",
    "Quaternion",
    "StreamNotEnabledError",
    "StreamType",
    "TrackingConfidence",
    "TrackingState",
    "Vector3",
    "Vector4",
    "__version__",
    "draw_all_skeletons",
    "draw_audio_radar",
    "draw_audio_visual_overlay",
    "draw_body_skeleton",
    "find_speaking_body",
    "save_point_cloud_ply",
    "to_open3d_point_cloud",
]
